### ISSUE TITLE
Items

### ISSUE THREAD

**Issue by Sparce1** [smallo92/CustomBuildingItems#1]
Items in the building section don't show up after knowing enough to fill up the rows
![20210408220116_1 - Copy](https://user-images.githubusercontent.com/82190821/114118051-062cc800-98b6-11eb-855f-f76e14b4cc1f.jpg)

**Comment by smallo92** [comment]
You didn't read the depdencies I listed on the mod page. I said you need [Build Expansion](https://valheim.thunderstore.io/package/MixoneFinallyHere/BuildExpansion/)
